---
settings:
parallel: true

driver: vagrant
provisioner:
  name: chef_zero
  require_chef_omnibus: latest


platforms:
- name: centos-6.4
- name: ubuntu-12.04

suites:
- name: default
  run_list:
    - recipe[ktc-testing]
    - recipe[etcd::compile_time]
    - recipe[ktc-monitor::client]
    - recipe[ktc-rsyslog]
  attributes:
    rsyslog:
      logstash_server: 'localhost'
      protocol: 'tcp'
    etcd:
      addr: 127.0.0.1
      peer_addr: 127.0.0.1
      servers:
        - 127.0.0.1
    ha_disabled: true
